### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by michelefa1988** [bitnami/bitnami-docker-pgbouncer#11]
Will there be an official helm chart for this?

**Comment by carrodher** [comment]
Thanks for your suggestion! Although it is not an application that is in our roadmap, we will check it internally and evaluate the feasibility but due to limited resources that could take some time.
 
If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.
